language: java
jdk:
  - oraclejdk8

before_script:

- export TZ=Asia/Shanghai


install:
- wget https://services.gradle.org/distributions/gradle-4.0.1-bin.zip
- mkdir /opt/gradle
- unzip -d /opt/gradle gradle-4.0.1-bin.zip
- rm gradle-4.0.1-bin.zip
- export PATH=$PATH:/opt/gradle/gradle-4.0.1/bin

script:

- gradle build
- gradle test
- gradle disttar

after_success:

